language: node_js
dist: trusty
node_js:
- "10"
- "9"
- "8"
- "7"
before_install:
- npm i -g npm@latest
install:
- npm i
script:
- npm run lint || true
- for file in chi/*; do node dist/cli.js $file; done;